# Site settings
author: Ben Jones
title: The Coding Journey
header-img: img/home-bg.png
email: bljones36@gmail.com
copyright_name: Ben Jones
description: > # this means to ignore newlines until "baseurl:"
  Ben Jones Codes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  inception88

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
